MODULE_TOPDIR = ../../../grass7.0/grass_trunk

SUBDIRS = \
	  v.fuzzy.select\
	  v.fuzzy.calibrator\
	  v.fuzzy.model\
	  r.fuzzy.model

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs

