MODULE_TOPDIR = ../../../grass7.0/grass_trunk


SUBDIRS = \
	  v.fuzzy.select \
	  v.fuzzy.calibrator \
	  v.fuzzy.model \
	  r.fuzzy.model \
	  t.rast.RothCEquilibrium \
	  t.rast.RothCModel

PGM = tag2e

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs

